[build-system]
requires = ["setuptools>=65.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "crypto-dashboard"
dependencies = [
    "streamlit>=1.28.0",
    "pandas>=2.1.0",
    "plotly>=5.15.0",
    "requests>=2.31.0",
    "numpy>=1.26.4"
]
